[project]
name = "llmtest-needleinahaystack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate==0.28.0",
    "anthropic>=0.7.5",
    "huggingface-hub>=0.23.2",
    "jsonargparse==4.27.5",
    "langchain==0.1.9",
    "langchain-community>=0.0.24",
    "langchain-core==0.1.26",
    "langsmith>=0.1.8",
    "langchain-openai",
    "langchain-anthropic",
    "openai>=1.3.5",
    "python-dotenv==1.0.0",
    "tiktoken>=0.5.1",
    "tokenizers>=0.20.0",
    "transformers>=4.46.0",
    "pytest==8.1.1",
    "ollama>=0.6.1",
    "pandas>=2.3.3",
    "seaborn>=0.13.2",
    "protobuf>=6.33.2",
    "hf>=1.1.0",
]
